version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ai_engine_ollama
    restart: unless-stopped

    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - internal_net

  api:
    build: .
    container_name: ai_engine_api
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app                 # Map code
      - ./api_data:/app/data   # Map thư mục data chứa json config
      - ./data:/app/data
    depends_on:
      - ollama
    networks:
      - internal_net
      - moodle_public_net

networks:
  internal_net:
    driver: bridge
  moodle_public_net:
    external: true
    name: ${MOODLE_NETWORK_NAME}